#include<bits/stdc++.h>    
using namespace std;
main()
{
    long long n;
    cin>>n;
    int count=0;
    while(n!=0)
    {
        if(n>=100)
        {
            count++;
            n-=100;
            continue;
        }
        if(n>=20)
        {
            count++;
            n-=20;
            continue;
        }
        if(n>=10)
        {
            count++;
            n-=10;
            continue;
        }
        if(n>=5)
        {
            count++;
            n-=5;
            continue;
        }
        if(n>=1)
        {
            count++;
            n-=1;
            continue;
        }
    }
    cout<<count;
}